A knitr document
======================

## Introduction

```{r setoptions, echo = FALSE}
library(knitr)
opts_chunk$set(echo = FALSE, results = "hide")
# global options set
```

### General

This is some text as text chunk.

Here is a code chunk:
```{r cache = TRUE}
# can cache the result to save some time
set.seed(1)
x <- rnorm(100)
mean(x)
```

### Adding and calling variables

```{r computetime, echo = FALSE}
time <- format(Sys.time(), "%a %b %d %H %Y")
rand <- rnorm(1)
```

The current time is `r time`.

Here is a random number `r rand`

### Incorporating Graphics

Let's first simulate some data
```{r simulatedata, echo = TRUE}
x <- rnorm(100)
y <- x + rnorm(100, sd = 0.5)
```

Here is a scatterplot of the data generated:
```{r scatterplot, fig.height = 4}
par(mar = c(5, 4, 1, 1), las = 1)
plot(x, y, main = "My simulated Data")

```

### Making table with xtable

```{r fitmodel}
library(datasets)
data(airquality)
fit <- lm(Ozone ~ Wind + Temp + Solar.R, data = airquality)
```

Here is a table of the regression coefficients.
```{r showtable, results = "asis"}
library(xtable)
xt <- xtable(summary(fit))
print(xt, type = "html")
```